CREATE TABLE Loja (
	Endereco VARCHAR(60) PRIMARY KEY NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	Telefone CHAR(9) NOT NULL,
)

CREATE TABLE Peca_do_Traje (
	ID CHAR(6) NOT NULL PRIMARY KEY ,
	Nome VARCHAR(60) NOT NULL,
	Tamanho VARCHAR(3) NOT NULL,
	Universidade VARCHAR(32) NOT NULL,
	Quantidade INT NOT NULL,
	End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco),
	Genero VARCHAR(1) NOT NULL,

)



CREATE TABLE Artigo_Academico (
	ID CHAR(6) NOT NULL PRIMARY KEY ,
	Nome VARCHAR(60) NOT NULL,
	Quantidade int NOT NULL,
	End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco),

)

CREATE TABLE Emblema (
	ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ,
	Forma VARCHAR(16) NOT NULL,
	Tipo VARCHAR (16) NOT NULL,
)

CREATE TABLE Pin (
	ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ,
	Tipo VARCHAR (16) NOT NULL,
)

CREATE TABLE Pasta (
	ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ,
	Universidade VARCHAR (32) NOT NULL,
)

CREATE TABLE Chapeu (
	ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ,
	Universidade VARCHAR (32) NOT NULL,
	Genero VARCHAR (16) NOT NULL,	
)

CREATE TABLE NoA (
	ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ,
	Cor1 VARCHAR (16) NOT NULL,
	Cor2 VARCHAR (16),
	Tipo VARCHAR (16) NOT NULL,
)

CREATE TABLE Traje (
	ID CHAR(6) NOT NULL PRIMARY KEY,
	Num_Acessorios int NOT NULL,
	Num_Pecas int NOT NULL,
	Completo Bit NOT NULL,
	End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco),
)

CREATE TABLE Peca_do_Traje_Comprada(
	ID_Traje CHAR(6) NOT NULL FOREIGN KEY REFERENCES Traje(ID),
	ID_Peca CHAR(6) NOT NULL FOREIGN KEY REFERENCES Peca_do_Traje(ID),
	PRIMARY KEY(ID_Traje, ID_Peca)
)

CREATE TABLE Artigo_Academico_Comprado(
	ID_Traje CHAR(6) NOT NULL FOREIGN KEY REFERENCES Traje(ID),
	ID_Artigo CHAR(6) NOT NULL FOREIGN KEY REFERENCES Artigo_Academico(ID),
	PRIMARY KEY(ID_Traje, ID_Artigo)
)

CREATE TABLE Artigo_Papelaria (
	ID CHAR(6) NOT NULL PRIMARY KEY ,
	Nome VARCHAR(30) NOT NULL,
	Marca VARCHAR(30) NOT NULL,
	Quantidade int NOT NULL,
	End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco),
)


CREATE TABLE Caneta (
	ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Papelaria (ID),
	Tipo VARCHAR(30) NOT NULL,
	Cor VARCHAR (16) NOT NULL,
)

CREATE TABLE Lapis (
	ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Papelaria (ID),
	Dureza VARCHAR(2) NOT NULL,
)

CREATE TABLE Fotocopiadora (
	ID CHAR(6) NOT NULL	PRIMARY KEY,
	Tipo VARCHAR(30) NOT NULL,
	End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco),
)


CREATE TABLE Fotocopia (
    Documento VARCHAR(60) NOT NULL PRIMARY KEY,
    ID_maquina CHAR(6) NOT NULL FOREIGN KEY REFERENCES Fotocopiadora (ID),
    Tipo_Papel VARCHAR(30) NOT NULL,
    Cores Bit NOT NULL,
) 