-- Drop tables if they exist
DROP TABLE IF EXISTS Fotocopia;
DROP TABLE IF EXISTS Fotocopiadora;
DROP TABLE IF EXISTS Lapis;
DROP TABLE IF EXISTS Caneta;
DROP TABLE IF EXISTS Artigo_Papelaria;
DROP TABLE IF EXISTS Artigo_Academico_Comprado;
DROP TABLE IF EXISTS Peca_do_Traje_Comprada;
DROP TABLE IF EXISTS Traje;
DROP TABLE IF EXISTS NoA;
DROP TABLE IF EXISTS Chapeu;
DROP TABLE IF EXISTS Pasta;
DROP TABLE IF EXISTS Pin;
DROP TABLE IF EXISTS Emblema;
DROP TABLE IF EXISTS Artigo_Academico;
DROP TABLE IF EXISTS Peca_do_Traje;
DROP TABLE IF EXISTS Loja;

-- Create tables
CREATE TABLE Loja (
    Endereco VARCHAR(60) PRIMARY KEY NOT NULL,
    Nome VARCHAR(30) NOT NULL,
    Telefone CHAR(9) NOT NULL
);

CREATE TABLE Peca_do_Traje (
    ID CHAR(6) NOT NULL PRIMARY KEY,
    Nome VARCHAR(60) NOT NULL,
    Tamanho VARCHAR(3) NOT NULL,
    Universidade VARCHAR(32) NOT NULL,
    Quantidade INT NOT NULL,
    End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco),
    Genero VARCHAR(1) NOT NULL
);

CREATE TABLE Artigo_Academico (
    ID CHAR(6) NOT NULL PRIMARY KEY,
    Nome VARCHAR(60) NOT NULL,
    Quantidade INT NOT NULL,
    End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco)
);

CREATE TABLE Emblema (
    ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    Forma VARCHAR(16) NOT NULL,
    Tipo VARCHAR(16) NOT NULL
);

CREATE TABLE Pin (
    ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    Tipo VARCHAR(16) NOT NULL
);

CREATE TABLE Pasta (
    ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    Universidade VARCHAR(32) NOT NULL
);

CREATE TABLE Chapeu (
    ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    Universidade VARCHAR(32) NOT NULL,
    Genero VARCHAR(16) NOT NULL
);

CREATE TABLE NoA (
    ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Academico (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    Cor1 VARCHAR(16) NOT NULL,
    Cor2 VARCHAR(16),
    Tipo VARCHAR(16) NOT NULL
);

CREATE TABLE Traje (
    ID CHAR(6) NOT NULL PRIMARY KEY,
    Nome VARCHAR(60) NOT NULL,
    Num_Acessorios INT NOT NULL,
    Num_Pecas INT NOT NULL,
    Completo BIT NOT NULL,
    End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco) 
);

CREATE TABLE Peca_do_Traje_Comprada (
    ID_Traje CHAR(6) NOT NULL,
    ID_Peca CHAR(6) NOT NULL,
    PRIMARY KEY(ID_Traje, ID_Peca),
    FOREIGN KEY (ID_Traje) REFERENCES Traje(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (ID_Peca) REFERENCES Peca_do_Traje(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE Artigo_Academico_Comprado (
    ID_Traje CHAR(6) NOT NULL,
    ID_Artigo CHAR(6) NOT NULL,
    PRIMARY KEY (ID_Traje, ID_Artigo),
    FOREIGN KEY (ID_Traje) REFERENCES Traje (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (ID_Artigo) REFERENCES Artigo_Academico (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Artigo_Papelaria (
    ID CHAR(6) NOT NULL PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL,
    Marca VARCHAR(30) NOT NULL,
    Quantidade INT NOT NULL,
    End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco) 
);

CREATE TABLE Caneta (
    ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Papelaria (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    Tipo VARCHAR(30) NOT NULL,
    Cor VARCHAR(16) NOT NULL
);

CREATE TABLE Lapis (
    ID CHAR(6) NOT NULL PRIMARY KEY REFERENCES Artigo_Papelaria (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    Dureza VARCHAR(2) NOT NULL
);

CREATE TABLE Fotocopiadora (
    ID CHAR(6) NOT NULL PRIMARY KEY,
    Tipo VARCHAR(30) NOT NULL,
    End_Loja VARCHAR(60) FOREIGN KEY REFERENCES Loja (Endereco) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Fotocopia (
    Documento VARCHAR(60) NOT NULL PRIMARY KEY,
    ID_maquina CHAR(6) NOT NULL FOREIGN KEY REFERENCES Fotocopiadora (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    Tipo_Papel VARCHAR(30) NOT NULL,
    Cores BIT NOT NULL
);
